#!/usr/bin/bash bash

# Exit on error
set -e

# Install virtualenv for managing virtual environments
pip install virtualenv

# Create and activate a new virtual environment
virtualenv .venv

# Activate the virtual environment
if test -d .venv/bin; then # (.venv/bin on Linux)
  source .venv/bin/activate
elif test -d .venv/Scripts; then # (.venv/Scripts on Windows)
  source .venv/Scripts/activate
else
  echo "Expected .venv/bin or .venv/Scripts to exist"
  exit 1
fi

# Install the project's dependencies in the virtual environment
pip install -r requirements.txt --no-warn-script-location
